env:
    type: triangle
    size: 6

agent:
    action_axes: 2
    episodes: 50
    greedy: False

    acm:
        actor:
            dimensions:
                - 24
                - 48
                - 1
            learning_rate: 0.05
            discount: 0.99
            elig_decay_rate: 0.99
            greed: 0
            greed_decay: 0.99
        critic_type: table
        critic:
            dimensions:
                - 24
                - 48
                - 1
            learning_rate: 0.05
            discount: 0.99
            elig_decay_rate: 0.99
            greed: 0
            greed_decay: 0.99

visual:
    resolution: 500
    peg_scale: 0.25
    board_scale: 1
    outline_color:
        - 255
        - 255
        - 255
    fill_color:
        - 127
        - 0
        - 0
