env:
    type: diamond
    size: 4

agent:
    action_axes: 2
    episodes: 1000
    greedy: False

    acm:
        actor:
            dimensions:
                - 24
                - 48
                - 1
            learning_rate: 0.05
            discount: 0.99
            elig_decay_rate: 0.99
            curiosity: 0.6
            curiosity_decay: 0.9995
        critic_type: table
        critic:
            dimensions:
                - 24
                - 48
                - 1
            learning_rate: 0.05
            discount: 0.99
            elig_decay_rate: 0.99
            curiosity: 1
            curiosity_decay: 0.9999

visual:
    resolution: 72
    peg_scale: 0.5
    board_scale: 1
    outline_color:
        - 255
        - 255
        - 255
    fill_color:
        - 127
        - 0
        - 0
